@echo off

start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
taskkill /f /im H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
taskkill /f /im H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
taskkill /f /im H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 8
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
timeout 12
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat
start H20Config.bat


pause
exit